export default {
  css: `.day-sheet{position:relative}.day-feedback{display:grid;gap:18px;margin-top:18px;padding:18px;border:1px solid var(--border-subtle);border-radius:var(--radius-lg);background:var(--surface-secondary);opacity:0;transform:translateY(8px);pointer-events:none;transition:opacity 180ms ease-out,transform 220ms cubic-bezier(.16,1,.3,1)}.day-sheet[data-complete] .minimal-rescue{display:none}.day-sheet[data-complete] .day-feedback{opacity:1;transform:none;pointer-events:auto}.day-week{display:grid;grid-template-columns:repeat(7,1fr);gap:7px}.day-cell{aspect-ratio:1;display:grid;place-items:center;border:1px solid var(--border-subtle);border-radius:8px;background:var(--progress-none);color:var(--text-muted);font:600 11px/1 var(--font-core)}.day-cell--built{background:var(--action-primary);color:var(--action-primary-fg)}.day-cell--today{position:relative;border-color:var(--state-adapted-fg);background:var(--state-adapted-bg);color:var(--state-adapted-fg);transform:scale(.7);animation:day-integrate 240ms cubic-bezier(.16,1,.3,1) 80ms forwards}.day-feedback__copy strong,.day-feedback__copy span{display:block;font-family:var(--font-core)}.day-feedback__copy strong{color:var(--text-primary);font-size:15px}.day-feedback__copy span{margin-top:4px;color:var(--text-secondary);font-size:13px}.day-feedback .feedback-button{width:100%;margin-top:0}@keyframes day-integrate{to{transform:scale(1)}}@media(prefers-reduced-motion:reduce){.day-feedback,.day-cell--today{transition-duration:1ms;animation-duration:1ms;animation-delay:0ms;transform:none}}`,
  render: () => `<article class="log-sheet day-sheet" role="dialog" aria-modal="true" aria-label="Registrar versión mínima"><div class="sheet-handle"></div><header class="sheet-head"><div class="habit-id"><span class="habit-mark">12</span><div><strong>Leer antes de dormir</strong><span>Día 12 de 30</span></div></div><button class="sheet-close" aria-label="Cerrar">×</button></header><p class="log-question">¿Cómo fue este día?</p><div class="log-levels"><button class="log-level">✓<span>Completo</span></button><button class="log-level" data-selected>−<span>Mínimo</span></button><button class="log-level">☾<span>Flexible</span></button></div><div class="minimal-rescue"><p>Una página mantiene el hábito disponible para mañana.</p><button class="minimal-trigger">Registrar mínimo</button></div><section class="day-feedback" role="status"><div class="day-week" aria-label="Semana actual: el miércoles quedó registrado como mínimo"><span class="day-cell day-cell--built">L</span><span class="day-cell day-cell--built">M</span><span class="day-cell day-cell--today">X</span><span class="day-cell">J</span><span class="day-cell">V</span><span class="day-cell">S</span><span class="day-cell">D</span></div><div class="day-feedback__copy"><strong>El día 12 cambió a Mínimo</strong><span>1 página · el hábito continúa disponible</span></div><button class="feedback-button">Listo</button></section></article>`,
  mount(root) {
    const sheet = root.querySelector('.day-sheet')
    root.querySelector('.minimal-trigger').addEventListener('click', () => { sheet.dataset.complete = '' })
    root.querySelector('.feedback-button').addEventListener('click', () => { sheet.hidden = true })
    root.querySelector('.sheet-close').addEventListener('click', () => { sheet.hidden = true })
  },
}
