export default {
  css: `.path-sheet{overflow:hidden}.path-form{transition:opacity 140ms ease-out,transform 180ms ease-out}.path-feedback{display:none;text-align:left}.path-sheet[data-complete] .path-form{display:none}.path-sheet[data-complete] .path-feedback{display:block;animation:path-feedback-in 220ms cubic-bezier(.16,1,.3,1) both}.path-feedback__label{margin:8px 0;color:var(--state-complete-fg);font:600 12px/1.3 var(--font-core);text-transform:uppercase;letter-spacing:.06em}.path-feedback h2{max-width:14ch;margin:0;color:var(--text-primary);font:600 32px/1.08 var(--font-core);letter-spacing:-.025em}.path-feedback>p{max-width:42ch;margin:12px 0 0;color:var(--text-secondary);font:400 14px/1.5 var(--font-core)}.habit-path{margin:22px 0 8px}.habit-path svg{width:100%;height:110px;display:block;overflow:visible}.habit-path path{fill:none;stroke-linecap:round}.habit-path__past{stroke:var(--progress-adapted);stroke-width:3;opacity:.55}.habit-path__new{stroke:var(--action-primary);stroke-width:3;stroke-dasharray:1;stroke-dashoffset:1;animation:habit-path-join 280ms cubic-bezier(.16,1,.3,1) 30ms forwards}.habit-path__future{stroke:var(--border-strong);stroke-width:2;stroke-dasharray:1 8}.habit-path circle{transform-box:fill-box;transform-origin:center;animation:path-node 180ms cubic-bezier(.16,1,.3,1) 170ms both}.habit-path__captions{display:flex;justify-content:space-between;gap:8px;color:var(--text-muted);font:500 12px/1.3 var(--font-core)}.habit-path__captions strong{color:var(--state-complete-fg)}@keyframes habit-path-join{to{stroke-dashoffset:0}}@keyframes path-node{from{opacity:0;transform:scale(.55)}to{opacity:1;transform:scale(1)}}@keyframes path-feedback-in{from{opacity:0;transform:translateY(7px)}to{opacity:1;transform:none}}@media(prefers-reduced-motion:reduce){.path-feedback,.habit-path__new,.habit-path circle{animation-duration:1ms;animation-delay:0ms}}`,
  render: () => `<article class="log-sheet path-sheet" role="dialog" aria-modal="true" aria-label="Registrar versión mínima"><div class="path-form"><div class="sheet-handle"></div><header class="sheet-head"><div class="habit-id"><span class="habit-mark">12</span><div><strong>Leer antes de dormir</strong><span>Día 12 de 30</span></div></div><button class="sheet-close" aria-label="Cerrar">×</button></header><p class="log-question">¿Cómo fue este día?</p><div class="log-levels"><button class="log-level">✓<span>Completo</span></button><button class="log-level" data-selected>−<span>Mínimo</span></button><button class="log-level">☾<span>Flexible</span></button></div><div class="minimal-rescue"><p>Una página mantiene el hábito disponible para mañana.</p><button class="minimal-trigger">Registrar mínimo</button></div></div><section class="path-feedback" role="status"><p class="path-feedback__label">Versión mínima registrada</p><h2>La trayectoria sigue unida.</h2><p>Una página fue suficiente para mantener disponible este hábito.</p><div class="habit-path" role="img" aria-label="El avance anterior se conecta con el mínimo de hoy y continúa hacia mañana"><svg viewBox="0 0 520 110" preserveAspectRatio="none" aria-hidden="true"><path class="habit-path__past" d="M6 74C88 74 102 34 180 34"/><path class="habit-path__new" pathLength="1" d="M180 34C268 34 278 82 360 65"/><path class="habit-path__future" d="M360 65C420 54 452 40 514 48"/><circle cx="360" cy="65" r="8" fill="var(--action-primary)" stroke="var(--surface-primary)" stroke-width="3"/></svg><div class="habit-path__captions"><span>Ayer</span><strong>Hoy · mínimo</strong><span>Mañana</span></div></div><button class="feedback-button">Cerrar registro</button></section></article>`,
  mount(root) {
    const sheet = root.querySelector('.path-sheet')
    root.querySelector('.minimal-trigger').addEventListener('click', () => { sheet.dataset.complete = '' })
    root.querySelector('.feedback-button').addEventListener('click', () => { sheet.hidden = true })
    root.querySelector('.sheet-close').addEventListener('click', () => { sheet.hidden = true })
  },
}
