/**
 * @file sw.js — Traker Service Worker
 *
 * Uses Workbox (injectManifest mode via vite-plugin-pwa).
 * self.__WB_MANIFEST is replaced at build time with the
 * precache manifest generated by vite-plugin-pwa.
 *
 * Responsibilities:
 *  1. Precache & serve the app shell (offline-first)
 *  2. Runtime cache strategies for external APIs
 *  3. Show push notifications (triggered from main thread via postMessage)
 *  4. Handle notification click → focus / open the app
 */

import { precacheAndRoute, cleanupOutdatedCaches } from 'workbox-precaching'
import { registerRoute } from 'workbox-routing'
import { NetworkFirst, CacheFirst } from 'workbox-strategies'
import { ExpirationPlugin } from 'workbox-expiration'
import { CacheableResponsePlugin } from 'workbox-cacheable-response'

// ── Precache app shell ─────────────────────────────────────────────────────
// __WB_MANIFEST is injected by vite-plugin-pwa at build time
precacheAndRoute(self.__WB_MANIFEST)
cleanupOutdatedCaches()

// ── Lifecycle: activate immediately ───────────────────────────────────────
self.skipWaiting()
self.addEventListener('activate', (event) => {
  event.waitUntil(self.clients.claim())
})

// ── Message handler: show notification from main thread ───────────────────
//
// Main thread posts: { type: 'SHOW_NOTIFICATION', title, options }
// SW calls showNotification() — works even when the tab is hidden.
//
self.addEventListener('message', (event) => {
  if (event.data?.type !== 'SHOW_NOTIFICATION') return

  const { title = 'Traker', options = {} } = event.data

  event.waitUntil(
    self.registration.showNotification(title, {
      icon:               '/favicon.svg',
      badge:              '/favicon.svg',
      vibrate:            [180, 80, 180],
      requireInteraction: false,
      silent:             false,
      ...options,
    })
  )
})

// ── Notification click: focus the app ────────────────────────────────────
self.addEventListener('notificationclick', (event) => {
  event.notification.close()

  const targetUrl = event.notification.data?.url ?? '/'

  event.waitUntil(
    self.clients
      .matchAll({ type: 'window', includeUncontrolled: true })
      .then((clientList) => {
        // If a tab is already open, focus it and navigate
        for (const client of clientList) {
          if ('focus' in client) {
            client.focus()
            if ('navigate' in client) client.navigate(targetUrl)
            return
          }
        }
        // Otherwise open a new window
        if (self.clients.openWindow) return self.clients.openWindow(targetUrl)
      })
  )
})

// ── Runtime caching ────────────────────────────────────────────────────────

// Google Fonts (if ever added) — cache-first, long TTL
registerRoute(
  /^https:\/\/fonts\.(googleapis|gstatic)\.com\/.*/i,
  new CacheFirst({
    cacheName: 'google-fonts',
    plugins: [
      new ExpirationPlugin({ maxEntries: 20, maxAgeSeconds: 60 * 60 * 24 * 365 }),
      new CacheableResponsePlugin({ statuses: [0, 200] }),
    ],
  })
)

// Supabase REST API — network-first, short TTL fallback
registerRoute(
  /^https:\/\/.*\.supabase\.co\/rest\/.*/i,
  new NetworkFirst({
    cacheName: 'supabase-api',
    networkTimeoutSeconds: 5,
    plugins: [
      new ExpirationPlugin({ maxEntries: 50, maxAgeSeconds: 60 * 5 }),
      new CacheableResponsePlugin({ statuses: [0, 200] }),
    ],
  })
)
