/**
 * @file sw.js — Traker Service Worker
 *
 * Uses Workbox (injectManifest mode via vite-plugin-pwa).
 * self.__WB_MANIFEST is replaced at build time with the
 * precache manifest generated by vite-plugin-pwa.
 *
 * Responsibilities:
 *  1. Precache & serve the app shell (offline-first)
 *  2. Runtime cache strategies for external APIs
 *  3. Show push notifications (triggered from main thread via postMessage)
 *  4. Handle notification click → focus / open the app
 */

import { cleanupOutdatedCaches, createHandlerBoundToURL, precacheAndRoute } from 'workbox-precaching'
import { NavigationRoute, registerRoute } from 'workbox-routing'
import { CacheFirst } from 'workbox-strategies'
import { ExpirationPlugin } from 'workbox-expiration'
import { CacheableResponsePlugin } from 'workbox-cacheable-response'
import { enqueueNotificationAction } from './features/notifications/actionQueue.js'
import { NOTIFICATION_ACTION_IDS } from '../supabase/functions/_shared/notification-actions.js'

// ── Precache app shell ─────────────────────────────────────────────────────
// __WB_MANIFEST is injected by vite-plugin-pwa at build time
precacheAndRoute(self.__WB_MANIFEST)
cleanupOutdatedCaches()

// Vue Router uses history mode. Serve the precached shell for in-scope
// navigations so direct routes such as /goals also open while offline.
registerRoute(new NavigationRoute(createHandlerBoundToURL('index.html')))

// ── Lifecycle: activate immediately ───────────────────────────────────────
self.skipWaiting()
self.addEventListener('activate', (event) => {
  event.waitUntil(self.clients.claim())
})

// ── Scope-aware URL helpers ────────────────────────────────────────────────
//
// On GitHub Pages the app lives under /traker/, so absolute paths like
// '/favicon.svg' resolve OUTSIDE the app (404). Always build URLs from
// the registration scope instead.
const SCOPE = self.registration.scope            // e.g. https://user.github.io/traker/

/** Resolve an app-relative path ('favicon.svg', 'habit/123') against the scope. */
function scopeUrl(path = '') {
  return new URL(String(path).replace(/^\//, ''), SCOPE).href
}

const NOTIFICATION_DEFAULTS = {
  icon:    scopeUrl('icons/pwa-192x192.png'),
  badge:   scopeUrl('icons/pwa-192x192.png'),
  vibrate: [180, 80, 180],
}

// ── Message handler: show notification from main thread ───────────────────
//
// Main thread posts: { type: 'SHOW_NOTIFICATION', title, options }
// SW calls showNotification() — works even when the tab is hidden.
//
self.addEventListener('message', (event) => {
  if (event.data?.type !== 'SHOW_NOTIFICATION') return

  const { title = 'Traker', options = {} } = event.data

  event.waitUntil(
    self.registration.showNotification(title, {
      ...NOTIFICATION_DEFAULTS,
      requireInteraction: false,
      silent:             false,
      ...options,
    })
  )
})

// ── Web Push: show notifications sent by the send-reminders function ──────
//
// Payload (JSON): { title, body, tag, data: { url } }
//
self.addEventListener('push', (event) => {
  let payload = {}
  try {
    payload = event.data?.json() ?? {}
  } catch {
    payload = { body: event.data?.text() ?? '' }
  }

  event.waitUntil(
    self.registration.showNotification(payload.title ?? 'Traker', {
      ...NOTIFICATION_DEFAULTS,
      body:     payload.body ?? '',
      tag:      payload.tag  ?? 'traker-push',
      renotify: true,
      data:     payload.data ?? {},
      actions:  Array.isArray(payload.actions) ? payload.actions : [],
    })
  )
})

// ── Push subscription rotated by the browser ──────────────────────────────
//
// Best effort: re-subscribe with the same key. The new endpoint is saved
// to Supabase the next time the app opens (ensurePushSubscription runs on
// every app start and upserts the current endpoint).
self.addEventListener('pushsubscriptionchange', (event) => {
  const oldSub = event.oldSubscription
  if (!oldSub?.options?.applicationServerKey) return

  event.waitUntil(
    self.registration.pushManager.subscribe({
      userVisibleOnly:      true,
      applicationServerKey: oldSub.options.applicationServerKey,
    }).catch(() => null)
  )
})

// ── Notification click: focus the app ────────────────────────────────────
//
// Plain click (no action button, or a platform that doesn't support them —
// e.g. iOS Safari never sends event.action) keeps the old behavior exactly:
// focus/open the app and navigate to data.url.
//
// A click on one of the reminder's action buttons ('done' | 'snooze' |
// 'skip', see notifications.service.js's HABIT_REMINDER_ACTIONS) instead
// posts a message to an open client so the app can act on it (mark the
// habit done/skipped, or reschedule a nudge) — the SW itself has no
// access to the Pinia stores. If habit-${id} is present in the tag we
// forward the habit id too.
self.addEventListener('notificationclick', (event) => {
  event.notification.close()

  // data.url is app-relative (e.g. '/habit/123'); resolve inside the scope
  const targetUrl = scopeUrl(event.notification.data?.url ?? '')
  const tagMatch = /^habit-(.+)$/.exec(event.notification.tag ?? '')
  const habitId = event.notification.data?.habitId ?? (tagMatch ? tagMatch[1] : null)
  const directAction = NOTIFICATION_ACTION_IDS.includes(event.action) && habitId
    ? enqueueNotificationAction({ action: event.action, habitId, url: targetUrl })
    : Promise.resolve(null)

  event.waitUntil(
    directAction.then(() => self.clients
      .matchAll({ type: 'window', includeUncontrolled: true })
      .then((clientList) => {
        if (event.action) {
          for (const client of clientList) {
            client.postMessage({ type: 'NOTIFICATION_ACTION_QUEUED' })
          }
          // Still bring the app to front so the user sees the result.
          const client = clientList.find(c => 'focus' in c)
          if (client) return client.focus()
          if (self.clients.openWindow) return self.clients.openWindow(targetUrl)
          return undefined
        }

        // If a tab is already open, focus it and navigate
        for (const client of clientList) {
          if ('focus' in client) {
            client.focus()
            if ('navigate' in client) client.navigate(targetUrl)
            return
          }
        }
        // Otherwise open a new window
        if (self.clients.openWindow) return self.clients.openWindow(targetUrl)
      })
    )
  )
})

// ── Runtime caching ────────────────────────────────────────────────────────

// Google Fonts (if ever added) — cache-first, long TTL
registerRoute(
  /^https:\/\/fonts\.(googleapis|gstatic)\.com\/.*/i,
  new CacheFirst({
    cacheName: 'google-fonts',
    plugins: [
      new ExpirationPlugin({ maxEntries: 20, maxAgeSeconds: 60 * 60 * 24 * 365 }),
      new CacheableResponsePlugin({ statuses: [0, 200] }),
    ],
  })
)
